### ISSUE TITLE
模块中引入的lots.util缺失

### ISSUE THREAD

**Issue by King-Of-BigHeart** [longavailable/hydrodata-crawler#2]
```python
if pathlib.Path('mytool/lots/util.py').is_file():
	from mytool.lots.util import recordExist_dict, writeLogsDicts2csv
else:
	from lots.util import recordExist_dict, writeLogsDicts2csv
```
基本每一个模块都有上述执行语句，但是代码中没有lots模块

**Comment by longavailable** [comment]
见自动化执行，
https://github.com/longavailable/hydrodata-crawler/blob/75698edb3d10e0f0b01bce64d822f269f26e0015/.github/workflows/crawl-hydrodata-datong.yml#L28

**Comment by longavailable** [comment]
https://github.com/longavailable/hydrodata-crawler/commit/75698edb3d10e0f0b01bce64d822f269f26e0015 这个提交是自动化脚本执行过程中出现的意外，mytool文件加不应出现的。

**Comment by King-Of-BigHeart** [comment]
好的，谢谢解惑，非常感谢

**Comment by longavailable** [comment]
lots是个人python库，已开源，见[longs-python-toolbox](https://github.com/longavailable/longs-python-toolbox)。

[longs-python-toolbox](https://github.com/longavailable/longs-python-toolbox)比较复杂（安装太麻烦），且大部分函数在这个项目中用不到，因此，在这个项目的自动化中仅作clone处理。
